[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "fontconfig",
  "glib",
  "gtk3",
  "libdrm",
  "libxkbcommon",
  "mesa",
  "pango",
  "cairo",
  "xorg.libX11",
  "xorg.libXcb",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "xorg.libXcursor",
  "xorg.libXi"
]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
